QUERY_EXECUTED_SUCCESS_MESSAGE = "Query executed successfully."
DATABASE_ERROR_MESSAGE = "Database error"
QUERY_INSERTED_SUCCESS_MESSAGE = "Insert query executed successfully."
FAILED_TO_ADD_MESSAGE = "Failed to add intern."
ADD_INTERN_SUCCESS_MESSAGE = "Added intern successfully."